services:
    tools:
        container_name: linkwarden-speeddial
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "9018:9018"
        volumes:
            - ./:/code
        networks:
            - bridged

networks:
    bridged:
        external: true
